#!/bin/bash
# clean.sh — Remove ALL build artifacts, caches, and generated files.
#
# Usage:
#   scripts/clean.sh           # Clean all build artifacts and frontend caches
#   scripts/clean.sh --c-only  # Clean only C build artifacts and generated C
#
# Ensures every subsequent full build starts from scratch — no cached .o files,
# no stale node_modules, no leftover dist folders. C-only callers can preserve
# frontend caches for faster local UI rebuilds.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
C_ONLY=false

for arg in "$@"; do
    case "$arg" in
        --c-only)
            C_ONLY=true
            ;;
        *)
            echo "Usage: scripts/clean.sh [--c-only]" >&2
            exit 2
            ;;
    esac
done

echo "=== Cleaning build artifacts ==="

# C build artifacts
rm -rf "$ROOT/build/c"

# Generated embedded assets (regenerated by embed-frontend.sh)
rm -f "$ROOT/src/ui/embedded_assets.c"

if ! $C_ONLY; then
    # Frontend build artifacts
    rm -rf "$ROOT/graph-ui/dist"
    rm -rf "$ROOT/graph-ui/node_modules"

    # Root-level node artifacts (if any)
    rm -rf "$ROOT/node_modules"
fi

# Leftover test fixture dirs (C test suite sometimes creates these in CWD)
find "$ROOT" -maxdepth 1 -type d \( -name 'cbm_*' -o -name 'cli-*' \) -exec rm -rf {} + 2>/dev/null || true

# Leftover test fixture dirs in /tmp
find /tmp -maxdepth 1 -type d \( -name 'cbm_*' -o -name 'cli-*' \) -user "$(id -u)" -exec rm -rf {} + 2>/dev/null || true

echo "=== Clean complete ==="
